MCU_FAMILY = NRF52
MCU_SERIES = NRF52840
MCU_LDSCRIPT = nrf52840_ao
MCU = cortex-m4

# Build Options
BOOTMAGIC_ENABLE = no
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = yes

CONSOLE_ENABLE = yes
COMMAND_ENABLE = yes

NKRO_ENABLE = no

BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = no

BLUETOOTH_ENABLE = no
AUDIO_ENABLE = no

COMBO_ENABLE = no
